### ISSUE TITLE
Can't compile project

### ISSUE THREAD

**Issue by bord81** [brorson/ADC-001_basic_code#1]
I've got BBB Rev. C and flashed Debian 9.2 image onto eMMC. I followed the steps in the instruction for ADC-001, but the compilation of PRU0 fails with the message (exec'd as root): "pru0.c", line 9: fatal error: cannot open source file "stdint.h"

I've tried also different Debian 7, 8 and 9 images with the same result. What should I change? Thanks.

**Comment by brorson** [comment]
That is interesting.  It's likely the compiler can't find stdint.h,
even though it's in the standard library.

Are you using my Makefile?  If not, please try using it.

If you're using my Makefile, the compiler can't find stdint.h for some
reason so you probably need to fiddle with
the include paths in Makefile.  Look into /usr/include and its
subdirectories.  Once you find stdint.h, then tell the compiler where to
find it by adding the path into the CFLAGS in the Makefile.  That is,
the the CFLAGS line will look something like this after you add your path:

CFLAGS := -O3 -mfpu=vfpv3 -mfloat-abi=hard -march=armv7 -I./include -I<your path here>

Best of luck,
Stuart Brorson

**Comment by bord81** [comment]
Adding -I//usr/share/ti/cgt-pru/include helped, however I got following warnings:

“pru0.c” , line 209:  warning: statement is unreachable
warning: automatic RTS selection: attempt to automatically link in index
	library “libc.a” failed: file not found
warning: entry-point symbol “_c_int00” undefined
warning: no suitable  entry-point found ; setting to 0
warning: section pru0.out(.resource_table) at 02000h falls in unconfigured
	memory (skipped)

“pru1.c” , line 52:  warning: statement is unreachable
warning: automatic RTS selection: attempt to automatically link in index
	library “libc.a” failed: file not found
warning: entry-point symbol “_c_int00” undefined
warning: no suitable  entry-point found ; setting to 0
warning: section pru1.out(.resource_table) at 02000h falls in unconfigured
	memory (skipped)
ADC_001-00A0.dtbo: Warning (unit_address_vs_reg): Node /fragment@0 has a unit name, but no reg property
ADC_001-00A0.dtbo: Warning (unit_address_vs_reg): Node /fragment@1 has a unit name, but no reg property

And main.o segfaults after printing: In prussdrv_open, opening /dev/uio0

Separately, there is an issue with fix_uio.sh:

Installing uio_pruss module .../fix_uio.sh: line 27: /sys/devices/bone_capemgr.9/slots: No such file or directory
.../fix_uio.sh: line 35: /sys/devices/bone_capemgr.9/slots: No such file or directory

**Comment by brorson** [comment]
Hi --

Regarding the PRU problems, it looks like the linker did not find
libc.a for the PRU.  Find where libc.a lives and provide a link to it
in the Makefile.

Regarding the unconfigured memory, this command file is supposed to
configure the memory during linking:

https://github.com/brorson/ADC-001_basic_code/blob/master/AM335x_PRU.cmd

Make sure you use it when linking.  Please look at my Makefile and see
what I did to link the project.

Regarding fix_uio.sh, it looks like you are using a more recent
Linux version than I developed on.  This script is not needed on newer
Linux distros for the Beaglebone.

I suggest you standardize on this image for your Beaglebone:

Debian 9.2 2017-10-10 4GB SD IoT

Available at https://beagleboard.org/latest-images

The reason is that every time the Beaglebone folks release a new Linux
version, they move things around and stuff gets broken.  That seems to
be your problem:  stuff has not been put in the place where my
software expects to see it.

Additionally, the biggest
problem is that they havea deprecated the uio system in favor of a
broken message passing interface.  Switching a new system back to UIO
is difficult.  The above image still uses UIO, and I recommend you use
it.

My last two projects (Anomaly Detector and MUSIC Algorithm) used the
above image.  I also have a document talking about how to configure
your Beaglebone under the MUSIC project directory here:

https://github.com/brorson/MusicPlaypen/blob/master/ConfiguringTheBB_Debian9.2.pdf

Good luck, and let me know how you manage!

Stuart

**Comment by bord81** [comment]
Hi,

Thanks for instructions, I compiled it!
Adding path to libc.a to PRU_CC_FLAGS did the trick.

However, it seems there is some issue with communication to cape.

The following command prints nothing:
cat /sys/kernel/debug/pinctrl/44e10800.pinmux/pinmux­pins | grep pru

And the multiple read test returns: 
"In spi_writeread_continuous, timed out waiting for end of transaction!"

**Comment by brorson** [comment]
Hi,

The UIO system maps the GPIO pins of the device into Linux's directory
and file system.  THat way you can read and write to a GPIO pin just
like you read and write files.  You can read about it in detail here:

https://www.kernel.org/doc/html/v4.18/driver-api/uio-howto.html

Texas Instruments provides a software layer utilizing the UIO stuff
which my code invokes.  That system is the PRUSS stuff which you find
in my code base (including prussdrv.h, etc).

If the UIO subsystem is not set up correctly, then you will have
problems like this:

>The following command prints nothing:
>cat /sys/kernel/debug/pinctrl/44e10800.pinmux/pinmux-pins | grep pru

Next, the .dts stuff sets up a "device tree" which provides a
description of the hardware to Linux.  You can read about device trees
here:

https://elinux.org/images/f/f9/Petazzoni-device-tree-dummies_0.pdf
http://www.ofitselfso.com/BeagleNotes/AboutTheDeviceTree.pdf

Your problem sounds like a device tree problem, or the UIO subsystem
is not initialized properly.  Maybe you are using a different Linux
version from me, and the UIO stuff is mapped to a different place in
the file system?  If so, then you need to make sure the .c programs
know where to look.

I suggest you read up on device trees and the UIO subsystem and then
work to make sure the pru pins show up when you issue this command:

cat /sys/kernel/debug/pinctrl/44e10800.pinmux/pinmux-pins | grep pru

Things to try include modifying uEnv.txt in /boot, as well as locating
where the pinmux-pins device ended up in your particular Linux distro.

Best regards,
Stuart

**Comment by bord81** [comment]
Ok, thank you very much, I'll try that.

Borys
